
name: Terraform Deployment

on:

  workflow_dispatch:

    inputs:

      environment:
        description: "Select environment"
        required: true
        type: choice

        options:
          - dev
          - test
          - ppe
          - prod

      terraform_action:
        description: "Select Terraform action"
        required: true
        type: choice

        options:
          - fmt
          - plan
          - apply


permissions:
  id-token: write
  contents: read


jobs:

  terraform:

    name: "${{ inputs.terraform_action }} - ${{ inputs.environment }}"

    runs-on: ubuntu-latest


    steps:

      # ---------------------------
      # 1. Checkout
      # ---------------------------

      - name: Checkout Repository

        uses: actions/checkout@v4


      # ---------------------------
      # 2. Install Terraform
      # ---------------------------

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

      - name: Check GitHub Context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event      : $GITHUB_EVENT_NAME"
          echo "Actor      : $GITHUB_ACTOR"
      
      # ---------------------------
      # 4. Debug GitHub OIDC Token
      # ---------------------------

      - name: Debug GitHub OIDC Token
        shell: bash
        run: |
          echo "Requesting GitHub OIDC token..."

          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')

          echo "OIDC token received successfully"
          echo "Token length: ${#TOKEN}"

          echo ""
          echo "OIDC Token Claims:"
          echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq '{
            iss,
            aud,
            sub,
            repository,
            repository_owner,
            ref,
            event_name,
            workflow,
            actor
          }'

      # ---------------------------
      # 3. Configure AWS OIDC
      # ---------------------------

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v6

        with:

          role-to-assume: "arn:aws:iam::905846954332:role/GitHubActionsTerraformRole"

          aws-region: ap-south-1


      # ---------------------------
      # 4. Terraform Init
      # ---------------------------

      - name: Terraform Init

        run: terraform init


      # ---------------------------
      # 5. Terraform Command
      # ---------------------------

      - name: Terraform Action

        run: |

          if [ "${{ inputs.terraform_action }}" == "fmt" ]; then

            terraform fmt -check

          elif [ "${{ inputs.terraform_action }}" == "plan" ]; then

            terraform plan \
              -var-file="environments/${{ inputs.environment }}/${{ inputs.environment }}.tfvars"

          elif [ "${{ inputs.terraform_action }}" == "apply" ]; then

            terraform apply \
              -var-file="environments/${{ inputs.environment }}/${{ inputs.environment }}.tfvars" \
              -auto-approve

          else

            echo "Invalid Terraform action"

            exit 1

          fi